[package]
name = "yew-toasts"
version = "0.1.1"
edition = "2024"
license = "MIT"
description = "Simple and easy toast notifications for Yew"
repository = "https://github.com/illuminodes/minions"
readme = "README.md"
homepage = "https://github.com/illuminodes/minions"


[dependencies]
web-sys = { version = "0.3", features = ["DomTokenList"] }
yew = { version = "0.21.0", features = ["csr"] }
